name: CD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Ambiente de deploy'
        required: true
        default: 'lab'
        type: choice
        options: [lab, develop]

jobs:
  build:
    uses: clefern/fiap-tc-mecanica-pipelines/.github/workflows/build.yml@develop
    with:
      service_name: inventory-service
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

  deploy:
    needs: [build]
    uses: clefern/fiap-tc-mecanica-pipelines/.github/workflows/deploy.yml@develop
    with:
      environment: ${{ inputs.environment }}
      k8s_deployment: inventory-service
      image_uri: ${{ needs.build.outputs.image-uri }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
