name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    uses: clefern/fiap-tc-mecanica-pipelines/.github/workflows/test.yml@develop
    with:
      service-name: inventory-service
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
